version: '3.8'

services:
  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=caroles-2017
      - DB_DATABASE=aws_db
      - DB_HOST=aws-db.ct5vhtaclqht.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: todo-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend